// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { authLoginData, authLoginErrors, authLoginResponses, authRecoverPasswordData, authRecoverPasswordResponses, authRegisterData, authRegisterErrors, authRegisterResponses, authResetPasswordData, authResetPasswordErrors, authResetPasswordResponses, devCreateUserData, devCreateUserResponses, eventsCreateEventData, eventsCreateEventResponses, eventsDeleteEventData, eventsDeleteEventErrors, eventsDeleteEventResponses, eventsReadBookmarkedEventsData, eventsReadBookmarkedEventsResponses, eventsReadEventData, eventsReadEventErrors, eventsReadEventResponses, eventsReadEventsData, eventsReadEventsResponses, eventsSetEventBookmarkData, eventsSetEventBookmarkErrors, eventsSetEventBookmarkResponses, eventsUpdateEventData, eventsUpdateEventErrors, eventsUpdateEventResponses, healthHealthCheckData, healthHealthCheckResponses, usersCreateUserData, usersCreateUserErrors, usersCreateUserResponses, usersDeleteUserData, usersDeleteUserErrors, usersDeleteUserMeData, usersDeleteUserMeResponses, usersDeleteUserResponses, usersReadUserByIdData, usersReadUserByIdErrors, usersReadUserByIdResponses, usersReadUserMeData, usersReadUserMeResponses, usersReadUsersData, usersReadUsersResponses, usersUpdatePasswordMeData, usersUpdatePasswordMeErrors, usersUpdatePasswordMeResponses, usersUpdateUserData, usersUpdateUserErrors, usersUpdateUserMeData, usersUpdateUserMeErrors, usersUpdateUserMeResponses, usersUpdateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class HealthService {
    /**
     * Health Check
     */
    public static healthCheck<ThrowOnError extends boolean = true>(options?: Options<healthHealthCheckData, ThrowOnError>) {
        return (options?.client ?? client).get<healthHealthCheckResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/health',
            ...options
        });
    }
}

export class AuthService {
    /**
     * Login
     */
    public static login<ThrowOnError extends boolean = true>(options: Options<authLoginData, ThrowOnError>) {
        return (options.client ?? client).post<authLoginResponses, authLoginErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Register
     */
    public static register<ThrowOnError extends boolean = true>(options: Options<authRegisterData, ThrowOnError>) {
        return (options.client ?? client).post<authRegisterResponses, authRegisterErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/auth/register',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Recover Password
     */
    public static recoverPassword<ThrowOnError extends boolean = true>(options?: Options<authRecoverPasswordData, ThrowOnError>) {
        return (options?.client ?? client).post<authRecoverPasswordResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/auth/password-recovery',
            ...options
        });
    }
    
    /**
     * Reset Password
     */
    public static resetPassword<ThrowOnError extends boolean = true>(options: Options<authResetPasswordData, ThrowOnError>) {
        return (options.client ?? client).post<authResetPasswordResponses, authResetPasswordErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/auth/reset-password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     */
    public static readUsers<ThrowOnError extends boolean = true>(options?: Options<usersReadUsersData, ThrowOnError>) {
        return (options?.client ?? client).get<usersReadUsersResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users',
            ...options
        });
    }
    
    /**
     * Create User
     */
    public static createUser<ThrowOnError extends boolean = true>(options: Options<usersCreateUserData, ThrowOnError>) {
        return (options.client ?? client).post<usersCreateUserResponses, usersCreateUserErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete User Me
     */
    public static deleteUserMe<ThrowOnError extends boolean = true>(options?: Options<usersDeleteUserMeData, ThrowOnError>) {
        return (options?.client ?? client).delete<usersDeleteUserMeResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me',
            ...options
        });
    }
    
    /**
     * Read User Me
     */
    public static readUserMe<ThrowOnError extends boolean = true>(options?: Options<usersReadUserMeData, ThrowOnError>) {
        return (options?.client ?? client).get<usersReadUserMeResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me',
            ...options
        });
    }
    
    /**
     * Update User Me
     */
    public static updateUserMe<ThrowOnError extends boolean = true>(options: Options<usersUpdateUserMeData, ThrowOnError>) {
        return (options.client ?? client).patch<usersUpdateUserMeResponses, usersUpdateUserMeErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Update Password Me
     */
    public static updatePasswordMe<ThrowOnError extends boolean = true>(options: Options<usersUpdatePasswordMeData, ThrowOnError>) {
        return (options.client ?? client).patch<usersUpdatePasswordMeResponses, usersUpdatePasswordMeErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me/password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete User
     */
    public static deleteUser<ThrowOnError extends boolean = true>(options: Options<usersDeleteUserData, ThrowOnError>) {
        return (options.client ?? client).delete<usersDeleteUserResponses, usersDeleteUserErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/{user_id}',
            ...options
        });
    }
    
    /**
     * Read User By Id
     */
    public static readUserById<ThrowOnError extends boolean = true>(options: Options<usersReadUserByIdData, ThrowOnError>) {
        return (options.client ?? client).get<usersReadUserByIdResponses, usersReadUserByIdErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/{user_id}',
            ...options
        });
    }
    
    /**
     * Update User
     */
    public static updateUser<ThrowOnError extends boolean = true>(options: Options<usersUpdateUserData, ThrowOnError>) {
        return (options.client ?? client).patch<usersUpdateUserResponses, usersUpdateUserErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/{user_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class EventsService {
    /**
     * Read Events
     */
    public static readEvents<ThrowOnError extends boolean = true>(options?: Options<eventsReadEventsData, ThrowOnError>) {
        return (options?.client ?? client).get<eventsReadEventsResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/events',
            ...options
        });
    }
    
    /**
     * Create Event
     */
    public static createEvent<ThrowOnError extends boolean = true>(options?: Options<eventsCreateEventData, ThrowOnError>) {
        return (options?.client ?? client).post<eventsCreateEventResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/events',
            ...options
        });
    }
    
    /**
     * Read Bookmarked Events
     */
    public static readBookmarkedEvents<ThrowOnError extends boolean = true>(options?: Options<eventsReadBookmarkedEventsData, ThrowOnError>) {
        return (options?.client ?? client).get<eventsReadBookmarkedEventsResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/events/bookmarked',
            ...options
        });
    }
    
    /**
     * Delete Event
     */
    public static deleteEvent<ThrowOnError extends boolean = true>(options: Options<eventsDeleteEventData, ThrowOnError>) {
        return (options.client ?? client).delete<eventsDeleteEventResponses, eventsDeleteEventErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/events/{id}',
            ...options
        });
    }
    
    /**
     * Read Event
     */
    public static readEvent<ThrowOnError extends boolean = true>(options: Options<eventsReadEventData, ThrowOnError>) {
        return (options.client ?? client).get<eventsReadEventResponses, eventsReadEventErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/events/{id}',
            ...options
        });
    }
    
    /**
     * Update Event
     */
    public static updateEvent<ThrowOnError extends boolean = true>(options: Options<eventsUpdateEventData, ThrowOnError>) {
        return (options.client ?? client).put<eventsUpdateEventResponses, eventsUpdateEventErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/events/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Set Event Bookmark
     */
    public static setEventBookmark<ThrowOnError extends boolean = true>(options: Options<eventsSetEventBookmarkData, ThrowOnError>) {
        return (options.client ?? client).put<eventsSetEventBookmarkResponses, eventsSetEventBookmarkErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/events/{id}/bookmark',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class DevService {
    /**
     * Create User
     */
    public static createUser<ThrowOnError extends boolean = true>(options?: Options<devCreateUserData, ThrowOnError>) {
        return (options?.client ?? client).post<devCreateUserResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/dev/users',
            ...options
        });
    }
}
