// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * DevUserCreate
 */
export type DevUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * EventBookmarkUpdate
 */
export type EventBookmarkUpdate = {
    /**
     * Is Bookmarked
     */
    is_bookmarked: boolean;
};

/**
 * EventCreate
 */
export type EventCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Venue Id
     */
    venue_id: string;
    /**
     * Performer Id
     */
    performer_id: string;
    /**
     * Time
     */
    time: string;
    /**
     * Price
     */
    price: number;
};

/**
 * EventDetail
 */
export type EventDetail = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Venue Id
     */
    venue_id: string;
    /**
     * Performer Id
     */
    performer_id: string;
    /**
     * Time
     */
    time: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Creator
     */
    creator: string;
    /**
     * Is Read
     */
    is_read?: boolean;
    /**
     * Is Bookmarked
     */
    is_bookmarked?: boolean;
    /**
     * Tickets
     */
    tickets: Array<TicketPublic>;
};

/**
 * EventPublic
 */
export type EventPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Venue Id
     */
    venue_id: string;
    /**
     * Performer Id
     */
    performer_id: string;
    /**
     * Time
     */
    time: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Creator
     */
    creator: string;
    /**
     * Is Read
     */
    is_read?: boolean;
    /**
     * Is Bookmarked
     */
    is_bookmarked?: boolean;
};

/**
 * EventUpdate
 */
export type EventUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Time
     */
    time?: string | null;
    /**
     * Performer Id
     */
    performer_id?: string | null;
};

/**
 * EventsPublic
 */
export type EventsPublic = {
    /**
     * Data
     */
    data: Array<EventPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PerformerGenre
 */
export type PerformerGenre = 'MUSIC' | 'SPORT' | 'THEATRE' | 'CIRCUS';

/**
 * PerformerMatch
 */
export type PerformerMatch = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    genre: PerformerGenre;
};

/**
 * PerformersMatch
 */
export type PerformersMatch = {
    /**
     * Data
     */
    data: Array<PerformerMatch>;
};

/**
 * RecoveryEmail
 */
export type RecoveryEmail = {
    /**
     * Email
     */
    email: string;
};

/**
 * TicketAvailability
 */
export type TicketAvailability = 'AVAILABLE' | 'BOOKED';

/**
 * TicketPublic
 */
export type TicketPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Row
     */
    row: number;
    /**
     * Seat
     */
    seat: number;
    /**
     * Price
     */
    price: number;
    availability: TicketAvailability;
    /**
     * User Id
     */
    user_id?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VenueMatch
 */
export type VenueMatch = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * VenuesMatch
 */
export type VenuesMatch = {
    /**
     * Data
     */
    data: Array<VenueMatch>;
};

export type healthHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type healthHealthCheckResponses = {
    /**
     * Response Health-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type healthHealthCheckResponse = healthHealthCheckResponses[keyof healthHealthCheckResponses];

export type authLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type authLoginErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authLoginError = authLoginErrors[keyof authLoginErrors];

export type authLoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type authLoginResponse = authLoginResponses[keyof authLoginResponses];

export type authRegisterData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type authRegisterErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authRegisterError = authRegisterErrors[keyof authRegisterErrors];

export type authRegisterResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type authRegisterResponse = authRegisterResponses[keyof authRegisterResponses];

export type authRecoverPasswordData = {
    body: RecoveryEmail;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password-recovery';
};

export type authRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authRecoverPasswordError = authRecoverPasswordErrors[keyof authRecoverPasswordErrors];

export type authRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type authRecoverPasswordResponse = authRecoverPasswordResponses[keyof authRecoverPasswordResponses];

export type authResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/auth/reset-password';
};

export type authResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authResetPasswordError = authResetPasswordErrors[keyof authResetPasswordErrors];

export type authResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type authResetPasswordResponse = authResetPasswordResponses[keyof authResetPasswordResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type eventsSuggestVenuesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/venues';
};

export type eventsSuggestVenuesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsSuggestVenuesError = eventsSuggestVenuesErrors[keyof eventsSuggestVenuesErrors];

export type eventsSuggestVenuesResponses = {
    /**
     * Successful Response
     */
    200: VenuesMatch;
};

export type eventsSuggestVenuesResponse = eventsSuggestVenuesResponses[keyof eventsSuggestVenuesResponses];

export type eventsSuggestPerformersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/performers';
};

export type eventsSuggestPerformersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsSuggestPerformersError = eventsSuggestPerformersErrors[keyof eventsSuggestPerformersErrors];

export type eventsSuggestPerformersResponses = {
    /**
     * Successful Response
     */
    200: PerformersMatch;
};

export type eventsSuggestPerformersResponse = eventsSuggestPerformersResponses[keyof eventsSuggestPerformersResponses];

export type eventsReadEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/events';
};

export type eventsReadEventsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsReadEventsError = eventsReadEventsErrors[keyof eventsReadEventsErrors];

export type eventsReadEventsResponses = {
    /**
     * Successful Response
     */
    200: EventsPublic;
};

export type eventsReadEventsResponse = eventsReadEventsResponses[keyof eventsReadEventsResponses];

export type eventsCreateEventData = {
    body: EventCreate;
    path?: never;
    query?: never;
    url: '/api/v1/events';
};

export type eventsCreateEventErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsCreateEventError = eventsCreateEventErrors[keyof eventsCreateEventErrors];

export type eventsCreateEventResponses = {
    /**
     * Successful Response
     */
    200: EventPublic;
};

export type eventsCreateEventResponse = eventsCreateEventResponses[keyof eventsCreateEventResponses];

export type eventsReadBookmarkedEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/events/bookmarked';
};

export type eventsReadBookmarkedEventsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsReadBookmarkedEventsError = eventsReadBookmarkedEventsErrors[keyof eventsReadBookmarkedEventsErrors];

export type eventsReadBookmarkedEventsResponses = {
    /**
     * Successful Response
     */
    200: EventsPublic;
};

export type eventsReadBookmarkedEventsResponse = eventsReadBookmarkedEventsResponses[keyof eventsReadBookmarkedEventsResponses];

export type eventsDeleteEventData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/events/{id}';
};

export type eventsDeleteEventErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsDeleteEventError = eventsDeleteEventErrors[keyof eventsDeleteEventErrors];

export type eventsDeleteEventResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type eventsDeleteEventResponse = eventsDeleteEventResponses[keyof eventsDeleteEventResponses];

export type eventsReadEventData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/events/{id}';
};

export type eventsReadEventErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsReadEventError = eventsReadEventErrors[keyof eventsReadEventErrors];

export type eventsReadEventResponses = {
    /**
     * Successful Response
     */
    200: EventDetail;
};

export type eventsReadEventResponse = eventsReadEventResponses[keyof eventsReadEventResponses];

export type eventsUpdateEventData = {
    body: EventUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/events/{id}';
};

export type eventsUpdateEventErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsUpdateEventError = eventsUpdateEventErrors[keyof eventsUpdateEventErrors];

export type eventsUpdateEventResponses = {
    /**
     * Successful Response
     */
    200: EventPublic;
};

export type eventsUpdateEventResponse = eventsUpdateEventResponses[keyof eventsUpdateEventResponses];

export type eventsSetEventBookmarkData = {
    body: EventBookmarkUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/events/{id}/bookmark';
};

export type eventsSetEventBookmarkErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsSetEventBookmarkError = eventsSetEventBookmarkErrors[keyof eventsSetEventBookmarkErrors];

export type eventsSetEventBookmarkResponses = {
    /**
     * Successful Response
     */
    200: EventPublic;
};

export type eventsSetEventBookmarkResponse = eventsSetEventBookmarkResponses[keyof eventsSetEventBookmarkResponses];

export type devCreateUserData = {
    body: DevUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/dev/users';
};

export type devCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type devCreateUserError = devCreateUserErrors[keyof devCreateUserErrors];

export type devCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type devCreateUserResponse = devCreateUserResponses[keyof devCreateUserResponses];
