// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * EventBookmarkUpdate
 */
export type EventBookmarkUpdate = {
    /**
     * Is Bookmarked
     */
    is_bookmarked: boolean;
};

/**
 * EventCreate
 */
export type EventCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Venue Id
     */
    venue_id: string;
    /**
     * Performer Id
     */
    performer_id: string;
    /**
     * Time
     */
    time: string;
    /**
     * Price
     */
    price: number;
};

/**
 * EventDetail
 */
export type EventDetail = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Venue Id
     */
    venue_id: string;
    /**
     * Performer Id
     */
    performer_id: string;
    /**
     * Time
     */
    time: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Creator
     */
    creator: string;
    /**
     * Is Read
     */
    is_read?: boolean;
    /**
     * Is Bookmarked
     */
    is_bookmarked?: boolean;
    /**
     * Tickets
     */
    tickets: Array<TicketPublic>;
};

/**
 * EventPublic
 */
export type EventPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Venue Id
     */
    venue_id: string;
    /**
     * Performer Id
     */
    performer_id: string;
    /**
     * Time
     */
    time: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Creator
     */
    creator: string;
    /**
     * Is Read
     */
    is_read?: boolean;
    /**
     * Is Bookmarked
     */
    is_bookmarked?: boolean;
};

/**
 * EventUpdate
 */
export type EventUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Time
     */
    time?: string | null;
    /**
     * Performer Id
     */
    performer_id?: string | null;
};

/**
 * EventsPublic
 */
export type EventsPublic = {
    /**
     * Data
     */
    data: Array<EventPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * TicketAvailability
 */
export type TicketAvailability = 'AVAILABLE' | 'BOOKED';

/**
 * TicketPublic
 */
export type TicketPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Row
     */
    row: number;
    /**
     * Seat
     */
    seat: number;
    /**
     * Price
     */
    price: number;
    availability: TicketAvailability;
    /**
     * User Id
     */
    user_id?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type eventsReadEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/events/';
};

export type eventsReadEventsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsReadEventsError = eventsReadEventsErrors[keyof eventsReadEventsErrors];

export type eventsReadEventsResponses = {
    /**
     * Successful Response
     */
    200: EventsPublic;
};

export type eventsReadEventsResponse = eventsReadEventsResponses[keyof eventsReadEventsResponses];

export type eventsCreateEventData = {
    body: EventCreate;
    path?: never;
    query?: never;
    url: '/api/v1/events/';
};

export type eventsCreateEventErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsCreateEventError = eventsCreateEventErrors[keyof eventsCreateEventErrors];

export type eventsCreateEventResponses = {
    /**
     * Successful Response
     */
    200: EventPublic;
};

export type eventsCreateEventResponse = eventsCreateEventResponses[keyof eventsCreateEventResponses];

export type eventsReadBookmarkedEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/events/bookmarked';
};

export type eventsReadBookmarkedEventsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsReadBookmarkedEventsError = eventsReadBookmarkedEventsErrors[keyof eventsReadBookmarkedEventsErrors];

export type eventsReadBookmarkedEventsResponses = {
    /**
     * Successful Response
     */
    200: EventsPublic;
};

export type eventsReadBookmarkedEventsResponse = eventsReadBookmarkedEventsResponses[keyof eventsReadBookmarkedEventsResponses];

export type eventsDeleteEventData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/events/{id}';
};

export type eventsDeleteEventErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsDeleteEventError = eventsDeleteEventErrors[keyof eventsDeleteEventErrors];

export type eventsDeleteEventResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type eventsDeleteEventResponse = eventsDeleteEventResponses[keyof eventsDeleteEventResponses];

export type eventsReadEventData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/events/{id}';
};

export type eventsReadEventErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsReadEventError = eventsReadEventErrors[keyof eventsReadEventErrors];

export type eventsReadEventResponses = {
    /**
     * Successful Response
     */
    200: EventDetail;
};

export type eventsReadEventResponse = eventsReadEventResponses[keyof eventsReadEventResponses];

export type eventsUpdateEventData = {
    body: EventUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/events/{id}';
};

export type eventsUpdateEventErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsUpdateEventError = eventsUpdateEventErrors[keyof eventsUpdateEventErrors];

export type eventsUpdateEventResponses = {
    /**
     * Successful Response
     */
    200: EventPublic;
};

export type eventsUpdateEventResponse = eventsUpdateEventResponses[keyof eventsUpdateEventResponses];

export type eventsSetEventBookmarkData = {
    body: EventBookmarkUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/events/{id}/bookmark';
};

export type eventsSetEventBookmarkErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsSetEventBookmarkError = eventsSetEventBookmarkErrors[keyof eventsSetEventBookmarkErrors];

export type eventsSetEventBookmarkResponses = {
    /**
     * Successful Response
     */
    200: EventPublic;
};

export type eventsSetEventBookmarkResponse = eventsSetEventBookmarkResponses[keyof eventsSetEventBookmarkResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
