// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * EventBookmarkUpdate
 */
export type EventBookmarkUpdate = {
    /**
     * Is Bookmarked
     */
    is_bookmarked: boolean;
};

/**
 * EventUpdate
 */
export type EventUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Time
     */
    time?: string | null;
    /**
     * Performer Id
     */
    performer_id?: string | null;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type healthHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type healthHealthCheckResponses = {
    /**
     * Response Health-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type healthHealthCheckResponse = healthHealthCheckResponses[keyof healthHealthCheckResponses];

export type authLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type authLoginErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authLoginError = authLoginErrors[keyof authLoginErrors];

export type authLoginResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type authRegisterData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type authRegisterErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authRegisterError = authRegisterErrors[keyof authRegisterErrors];

export type authRegisterResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type authRecoverPasswordData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password-recovery';
};

export type authRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type authResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/auth/reset-password';
};

export type authResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authResetPasswordError = authResetPasswordErrors[keyof authResetPasswordErrors];

export type authResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type eventsReadEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/events';
};

export type eventsReadEventsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type eventsCreateEventData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/events';
};

export type eventsCreateEventResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type eventsReadBookmarkedEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/events/bookmarked';
};

export type eventsReadBookmarkedEventsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type eventsDeleteEventData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/events/{id}';
};

export type eventsDeleteEventErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsDeleteEventError = eventsDeleteEventErrors[keyof eventsDeleteEventErrors];

export type eventsDeleteEventResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type eventsReadEventData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/events/{id}';
};

export type eventsReadEventErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsReadEventError = eventsReadEventErrors[keyof eventsReadEventErrors];

export type eventsReadEventResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type eventsUpdateEventData = {
    body: EventUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/events/{id}';
};

export type eventsUpdateEventErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsUpdateEventError = eventsUpdateEventErrors[keyof eventsUpdateEventErrors];

export type eventsUpdateEventResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type eventsSetEventBookmarkData = {
    body: EventBookmarkUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/events/{id}/bookmark';
};

export type eventsSetEventBookmarkErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type eventsSetEventBookmarkError = eventsSetEventBookmarkErrors[keyof eventsSetEventBookmarkErrors];

export type eventsSetEventBookmarkResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type devCreateUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dev/users';
};

export type devCreateUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
